const SET_INPUT = "SET_INPUT";
const SET_LOADING = "SET_LOADING";
const SET_QUIZES = "SET_QUIZES";
const NEXT_QUESTION = "NEXT_QUESTION";

export { SET_INPUT, SET_LOADING, SET_QUIZES, NEXT_QUESTION };
